wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1686841834.094019
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 19
      - 23
      4: 3.8.10
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
      10:
      - 9
dropout:
  desc: null
  value: 0.2
